# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of the node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Accord test runner
on:
  push:
    branches: main

env:
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /accord
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /accord
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
  ABLY_API_KEY_PUBLISH_SUBSCRIBE: ${{ secrets.ABLY_API_KEY_PUBLISH_SUBSCRIBE }}
  
defaults:
  run:
    working-directory: ./Application
    
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "20.x"
    - name: Installing node_modules for the workflow
      run: npm install -g npm
    - name: Force installing Jest for the workflow
      run: npm install --save-dev jest
    - name: Run tests suite with Jest
      run: npm run test:jest
