# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of the node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Accord test runner
on:
  push:
    branches: main
defaults:
  run:
    working-directory: ./Application
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "20.x"
    - name: Installing node_modules for the workflow
      run: npm install -g npm
    - name: Force installing Jest for the workflow
      run: npm install --save-dev jest
    - name: Run tests suite with Jest and manually added env
      env:  # Adding environment variable here
        MONGODB_USERNAME: baopham
        MONGODB_PASSWORD: Yjs12l26LZegm0VH
        MONGODO_URI: mongodb+srv://baopham:Yjs12l26LZegm0VH@accord-systems.umbugbv.mongodb.net/?retryWrites=true&w=majority&appName=Accord-Systems
      run: npm run test:jest
