# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of the node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Accord test runner

on:
  push:
    branches: main

defaults:
  run:
    working-directory: ./Application/Frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "10.x"
    - run: npm install -g npm
    - run: npm test:jest
